"__ct__Q23g3d4RootFRCQ23g3d11RootContext" 					= 0x8019b9c8;
"sceneClear__Q23g3d4RootFv" 								= 0x8019bc14;
"sceneDrawOpa__Q23g3d4RootCFv"								= 0x8019bda0;

"__ct__Q23g3d11RootContextFRQ23mem10IAllocatorUlUlUlUl" 	= 0x8019bff4;

"DefaultModelBufferOption__Q23g3d12ModelContextFv" 			= 0x80199af0;
"DefaultAllocator__Q23g3d12ModelContextFv" 					= 0x80199ae8;

"__ct__Q23g3d17CharaModelContextFRCQ23g3d15ResModelContextRCQ23g3d17ModelBufferOptionUlUlUlRQ23mem10IAllocatorbUlRCQ33hel6common15FixedString<32>" = 0x80195048;

"__ct__Q23g3d10CharaModelFRCQ23g3d17CharaModelContext"		= 0x801947f4;
"registerToRoot__Q23g3d10CharaModelFRQ23g3d4Root" 			= 0x80194964;
"updateWorldMtx__Q23g3d10CharaModelFv" 						= 0x801949c0;
"setModelRTMtx__Q23g3d10CharaModelFRCQ33hel4math8Matrix34" 	= 0x801949ec;
"setModelScale__Q23g3d10CharaModelFRCQ33hel4math7Vector3"	= 0x80194a24;

"__ct__Q23g3d17ResFileRepositoryFv"							= 0x8019b178;
"get__Q23g3d17ResFileRepositoryFPCcb"						= 0x8019b2f0;

"__ct__Q23g3d15ResFileAccessorFRCQ34nw4r3g3d7ResFile"		= 0x8014ccf4;

"__ct__Q23g3d15ResModelContextFRCQ23g3d15ResFileAccessorPCc"= 0x8019b6e8;