"DrawQuadFill__Q23gfx12EasyRender3DFRCQ33hel4math8Matrix34RCQ33hel4math7Vector3RCQ33hel4math7Vector3RCQ33hel4math7Vector3RCQ33hel4math7Vector3" = 0x8019cfc0;
"DrawLine__Q23gfx12EasyRender3DFRCQ33hel4math8Matrix34RCQ33hel4math7Vector3RCQ33hel4math7Vector3f" 												= 0x8019d488;
"SetViewMtx__Q23gfx12EasyRender3DFRCQ33hel4math8Matrix34" 																						= 0x8019cd70;
"SetColor__Q23gfx12EasyRender3DFRC8_GXColor" 																									= 0x8019cd40;
"SetupGX__Q23gfx12EasyRender3DFRCQ33hel4math8Matrix44b" 																						= 0x8019cab0;

"GXSetZMode" = 0x80038940;

"CurrentGameWidth__Q23gfx7UtilityFv" 	= 0x8019f4ac;
"CurrentGameHeight__Q23gfx7UtilityFv" 	= 0x8019f4d8;

"object__Q33hel6common35ExplicitSingleton<Q23gfx9VISetting>" = 0x808c1d78;

"__ct__Q34nw4r3g3d8LightObjFv" 						= 0x800dc800;
"Clear__Q34nw4r3g3d8LightObjFv" 					= 0x800f0e70;
"InitLightPos__Q34nw4r3g3d8LightObjFfff" 			= 0x800f0ec0;
"InitLightDir__Q34nw4r3g3d8LightObjFfff" 			= 0x800f0f00;
"InitLightColor__Q34nw4r3g3d8LightObjF8_GXColor" 	= 0x800f0e90;
"InitLightShininess__Q34nw4r3g3d8LightObjFf" 		= 0x800f1080;
"InitLightSpot__Q34nw4r3g3d8LightObjFf9_GXSpotFn"	= 0x800f0f40;
"InitLightAttnA__Q34nw4r3g3d8LightObjFfff"			= 0x800f0f80;
"InitLightAttnK__Q34nw4r3g3d8LightObjFfff"			= 0x800f1000;
"__as__Q34nw4r3g3d8LightObjFRCQ34nw4r3g3d8LightObj" = 0x800f0e20;

"disableLightObj__Q23g3d16LightSetAccessorCFUl" 							= 0x80195f40;
"disableLightObjAll__Q23g3d16LightSetAccessorCFv" 							= 0x80195f48;
"enableAmbientLightObj__Q23g3d16LightSetAccessorCFUl" 						= 0x80195f94;
"enableLightObj__Q23g3d16LightSetAccessorCFUlUl" 							= 0x80195f3c;
"setAmbientLightObj__Q23g3d16LightSetAccessorCFRCQ34nw4r3g3d11AmbLightObj" 	= 0x80195fd4;
"setLightObj__Q23g3d16LightSetAccessorCFUlRCQ34nw4r3g3d8LightObj" 			= 0x80195fa0;