"DrawQuadFill__Q23gfx12EasyRender3DFRCQ33hel4math8Matrix34RCQ33hel4math7Vector3RCQ33hel4math7Vector3RCQ33hel4math7Vector3RCQ33hel4math7Vector3" = 0x8019cfc0;
"DrawLine__Q23gfx12EasyRender3DFRCQ33hel4math8Matrix34RCQ33hel4math7Vector3RCQ33hel4math7Vector3f" 												= 0x8019d488;
"SetViewMtx__Q23gfx12EasyRender3DFRCQ33hel4math8Matrix34" 																						= 0x8019cd70;
"SetColor__Q23gfx12EasyRender3DFRC8_GXColor" 																									= 0x8019cd40;
"SetupGX__Q23gfx12EasyRender3DFRCQ33hel4math8Matrix44b" 																						= 0x8019cab0;
"t_loadPosMtx__26@unnamed@EasyRender3D_cpp@FRCQ33hel4math8Matrix34" = 0x8019ca20;

"block__Q23mem9DataBlockCFv" = 0x80189b18;
"sceneHeap__Q23mem6MemoryFv" = 0x801cc79c;
"mem2FixHeap__Q23mem6MemoryFv" = 0x801cc7a4;
"externalHeap__Q23mem6MemoryFv" = 0x801cc7ac;

"GXSetZMode" = 0x80038940;
"GXSetCopyClear" = 0x80035a00;
"GXSetBlendMode" = 0x80038850;
"GXBegin" = 0x80035390;
"GXInitTexObj" = 0x800368d0;
"GXLoadTexObj" = 0x80036f50;
"GXSetNumTexGens" = 0x80034880;
"GXSetNumTevStages" = 0x80038380;
"GXSetTevOrder" = 0x80038220;
"GXSetTevColor" = 0x80037EC0;
"GXSetTexCoordGen2" = 0x80034630;
"GXSetTevSwapMode" = 0x80038090;
"GXSetTevOp" = 0x80037ce0;
"GXSetTevSwapModeTable" = 0x800380D0;
"GXPixModeSync" = 0x80034D60;
"GXTexModeSync" = 0x80034D90;
"GXSetNumChans" = 0x80036600;
"GXSetCullMode" = 0x80035680;

"__ct__Q23gfx9TexBufferFRQ23mem10IAllocatorUsUs9_GXTexFmt" = 0x8019eb94;
"__dt__Q23gfx9TexBufferFv" = 0x8019ec3c;

"CurrentGameWidth__Q23gfx7UtilityFv" 	= 0x8019f4ac;
"CurrentGameHeight__Q23gfx7UtilityFv" 	= 0x8019f4d8;
"ClearZBuffer__Q23gfx7UtilityFf"		= 0x8019f514;

"CaptureEFB__Q23sfx7UtilityFRQ23gfx9TexBuffer9_GXTexFmtb" = 0x807017a4;
"FullScreenPlateDraw__Q23sfx7UtilityFb" = 0x8070191c;

"__ct__Q34nw4r3g3d8LightObjFv" 						= 0x800dc800;
"Clear__Q34nw4r3g3d8LightObjFv" 					= 0x800f0e70;
"InitLightPos__Q34nw4r3g3d8LightObjFfff" 			= 0x800f0ec0;
"InitLightDir__Q34nw4r3g3d8LightObjFfff" 			= 0x800f0f00;
"InitLightColor__Q34nw4r3g3d8LightObjF8_GXColor" 	= 0x800f0e90;
"InitLightShininess__Q34nw4r3g3d8LightObjFf" 		= 0x800f1080;
"InitLightSpot__Q34nw4r3g3d8LightObjFf9_GXSpotFn"	= 0x800f0f40;
"InitLightAttnA__Q34nw4r3g3d8LightObjFfff"			= 0x800f0f80;
"InitLightAttnK__Q34nw4r3g3d8LightObjFfff"			= 0x800f1000;
"__as__Q34nw4r3g3d8LightObjFRCQ34nw4r3g3d8LightObj" = 0x800f0e20;

"disableLightObj__Q23g3d16LightSetAccessorCFUl" 							= 0x80195f40;
"disableLightObjAll__Q23g3d16LightSetAccessorCFv" 							= 0x80195f48;
"enableAmbientLightObj__Q23g3d16LightSetAccessorCFUl" 						= 0x80195f94;
"enableLightObj__Q23g3d16LightSetAccessorCFUlUl" 							= 0x80195f3c;
"setAmbientLightObj__Q23g3d16LightSetAccessorCFRCQ34nw4r3g3d11AmbLightObj" 	= 0x80195fd4;
"setLightObj__Q23g3d16LightSetAccessorCFUlRCQ34nw4r3g3d8LightObj" 			= 0x80195fa0;

"__dt__Q23gfx10TextureObjFv" = 0x801a79ac;