"__ct__Q33hel4math7Vector2Fv" = 0x801a6e24;

"__ct__Q33hel4math7Vector3Fv"						= 0x80182a78;
"__ct__Q33hel4math7Vector3Ffff"						= 0x800bdad0;
"__as__Q33hel4math7Vector3FRCQ33hel4math7Vector3"	= 0x80182ad0;
"__apl__Q33hel4math7Vector3FRCQ33hel4math7Vector3"	= 0x8018938c;
"__pl__Q33hel4math7Vector3CFRCQ33hel4math7Vector3"	= 0x8019cf3c;
"__mi__Q33hel4math7Vector3CFv"						= 0x801a76f4;
"__mi__Q33hel4math7Vector3CFRCQ33hel4math7Vector3"	= 0x80182dd0;
"__ml__Q33hel4math7Vector3CFf"						= 0x80182aec;
"__dv__Q33hel4math7Vector3CFf"						= 0x801cfde8;
"dot__Q33hel4math7Vector3CFRCQ33hel4math7Vector3"	= 0x80183f90;
"cross__Q33hel4math7Vector3CFRCQ33hel4math7Vector3" = 0x80189484;
"normalize__Q33hel4math7Vector3Fv"					= 0x801a6f9c;
"length__Q33hel4math7Vector3CFv"					= 0x80183ee8;

"__ct__Q33hel4math8Matrix34Fv"																			= 0x8019ca80;
"__as__Q33hel4math8Matrix34FRCQ33hel4math8Matrix34"														= 0x80182a8c;
"__ml__Q33hel4math8Matrix34CFRCQ33hel4math8Matrix34"													= 0x80182ec0;
"CreateScale__Q33hel4math8Matrix34FRCQ33hel4math7Vector3"												= 0x801a5f38;
"CreateTrans__Q33hel4math8Matrix34FRCQ33hel4math7Vector3"												= 0x801a5ee8;
"CreateRotAxisRad__Q33hel4math8Matrix34FRCQ33hel4math7Vector3f"											= 0x801a5f88;
"CreateRotAxisDeg__Q33hel4math8Matrix34FRCQ33hel4math7Vector3f"											= 0x801a5fec;
"CreateRotXYZRad__Q33hel4math8Matrix34FRCQ33hel4math7Vector3"											= 0x801a6050;
"CreateRotXYZDeg__Q33hel4math8Matrix34FRCQ33hel4math7Vector3"											= 0x801a60ac;
"CreateLookAt__Q33hel4math8Matrix34FRCQ33hel4math7Vector3RCQ33hel4math7Vector3RCQ33hel4math7Vector3"	= 0x801a6108;
"mul__Q33hel4math8Matrix34CFRCQ33hel4math7Vector3" 														= 0x801837e4;

"__ct__Q33hel4math8Matrix44Fv" = 0x801a64bc;
"CreatePerspective__Q33hel4math8Matrix44Fffff" = 0x801a6444;

"ZERO__Q33hel4math7Vector3" = 0x8088a760;
"BASIS_X__Q33hel4math7Vector3" = 0x8088a778;
"BASIS_Y__Q33hel4math7Vector3" = 0x8088a784;
"BASIS_Z__Q33hel4math7Vector3" = 0x8088a790;

"AbsF32__Q33hel4math4MathFf" 	= 0x80387a58;
"CosDegF__Q33hel4math4MathFf" 	= 0x80274620;
"CosFIdx__Q33hel4math4MathFf"		= 0x8019cfa8;
"SinFIdx__Q33hel4math4MathFf"		= 0x8019cfb4;

"pow" = 0x800147b0;
"asin" = 0x800147a0;

"PSQUATMultiply" 	= 0x80031950;
"PSMTXQuat" 		= 0x80030e20;
"C_QUATRotAxisRad"	= 0x800319b0;
"C_QUATMtx"			= 0x80031a50;